// trial_sequence.h — Auto-generated by inspect_stimuli_v3.ipynb
// DO NOT EDIT — re-run notebook to regenerate
// 24 trials, seed=12345
// Active stimuli and reps:
//   ChirpFwd: 3 reps
//   ChirpRev: 3 reps
//   NoiseLp100: 3 reps
//   NoiseLp500: 3 reps
//   Sine10Hz: 3 reps
//   Sine25Hz: 3 reps
//   Sine60Hz: 3 reps
//   Ramp: 3 reps
// Enum codes: 0=ChirpFwd 1=ChirpRev 2=NoiseLp100 3=NoiseLp500
//             4=Sine2 5=Sine10 6=Sine25 7=Sine60 8=Sine100 9=Sine500 10=Ramp

#pragma once
#include <avr/pgmspace.h>

const int TOTAL_TRIALS = 24;

const uint8_t TRIAL_SEQUENCE[24] PROGMEM = {
       5,      0,      2,      7,      4,      6,      6,      3,      1,      3,      3,      5,      1,      0,      6,      2,
       1,      2,      7,      4,      5,      0,      7,      4
};
